[package]
name = "socketioxide"
version = "0.5.1"
edition = "2021"
rust-version = "1.63.0"

authors = ["Théodore Prévot <"]
description = "Socket IO server implementation in rust as a Tower Service."
repository = "https://github.com/totodore/socketioxide"
homepage = "https://github.com/totodore/socketioxide"
keywords = ["socketio", "tower", "axum", "hyper", "websocket"]
categories = [
    "asynchronous",
    "network-programming",
    "web-programming::websocket",
]
license = "MIT"
readme = "../README.md"

[dependencies]
engineioxide = { path = "../engineioxide", version = "0.5.0" }
futures = "0.3.27"
tokio = "1.26.0"
serde = { version = "1.0.155", features = ["derive"] }
serde_json = "1.0.94"
tower = "0.4.13"
tower-http = "0.4.0"
http = "0.2.9"
http-body = "0.4.5"
tracing = "0.1.37"
thiserror = "1.0.40"
itertools = "0.11.0"
dashmap = "5.4.0"

[dev-dependencies]
axum = "0.6.18"
tokio = { version = "1.26.0", features = ["macros", "parking_lot"] }
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
tokio-tungstenite = "0.20.0"
hyper = { version = "0.14.25", features = [
    "http1",
    "http2",
    "server",
    "stream",
    "runtime",
    "client",
] }
