[package]
name = "engineioxide"
version = "0.5.1"
edition = "2021"
rust-version = "1.63.0"

authors = ["Théodore Prévot <"]
description = "Engine IO server implementation in rust as a Tower Service."
repository = "https://github.com/totodore/socketioxide"
homepage = "https://github.com/totodore/socketioxide"
keywords = ["engineio", "tower", "axum", "hyper", "websocket"]
categories = [
    "asynchronous",
    "network-programming",
    "web-programming::websocket",
]
license = "MIT"

[dependencies]
async-trait = "0.1.66"
base64 = "0.21.0"
bytes = "1.4.0"
futures = "0.3.27"
http = "0.2.9"
http-body = "0.4.5"
hyper = { version = "0.14.25", features = [
    "http1",
    "http2",
    "server",
    "stream",
    "runtime",
] }
pin-project = "1.0.12"
serde = { version = "1.0.155", features = ["derive"] }
serde_json = "1.0.94"
thiserror = "1.0.40"
tokio = "1.26.0"
tokio-tungstenite = "0.20.1"
tower = "0.4.13"
tracing = "0.1.37"
rand = "0.8.5"
base64id = { version = "0.3.1", features = ["std", "rand", "serde"] }
memchr = { version = "2.5.0", optional = true }
unicode-segmentation = { version = "1.10.1", optional = true }

[dev-dependencies]
criterion = { version = "0.5.1", features = ["html_reports", "async_tokio"] }
tokio = { version = "1.26.0", features = ["macros", "parking_lot"] }
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
hyper = { version = "0.14.25", features = [
    "http1",
    "http2",
    "server",
    "stream",
    "runtime",
    "client",
] }

[features]
default = ["v4"]
v4 = []
v3 = ["memchr", "unicode-segmentation"]

[[bench]]
name = "benchmark_polling"
harness = false
